project:
  type: website
  output-dir: _output
  title: "Tutorials for Quantum Toolbox in Julia"
  render:
    - "*.md"
    - "*.qmd"
    - "!README.md"             # ignore
    - "!CODE_OF_CONDUCT.md"    # ignore
    - "!tutorial_template.qmd" # ignore

website:
  title: "Tutorials for Quantum Toolbox in Julia"
  navbar:
    search: true
    left:
      - href: index.md
        text: Home
      - href: QuantumToolbox.jl/toc.md
        text: QuantumToolbox.jl
      - href: HierarchicalEOM.jl/toc.md
        text: HierarchicalEOM.jl
    tools:
      - icon: github
        href:  https://github.com/qutip/qutip-julia-tutorials

bibliography: bibliography.bib  

format:
  html:
    theme:
      light: flatly
      dark: darkly
    highlight-style: atom-one
    css: styles.css
    toc: true
    code-line-numbers: true
    colorlinks: true
    footnotes-hover: true
    fig-align: center
    fig-responsive: true

execute:
  eval: true
  cache: true
  freeze: false
