name: Quarto PR preview

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      actions: write  # needed to allow julia-actions/cache to delete old caches that it has created
      contents: write # needed for Quarto render
      pull-requests: write # for GitHub action bot to write messages
    if: ${{ !github.event.pull_request.draft }}
    steps:
      - uses: actions/checkout@v5
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
      - uses: julia-actions/setup-julia@v2
        with:
          version: '1'
      - uses: julia-actions/cache@v2
      - uses: julia-actions/julia-buildpkg@v1
        with:
          precompile: true
      - name: Fix Timestamps
        run: bash .github/scripts/fix-timestamps
      - name: Quarto Render
        uses: quarto-dev/quarto-actions/render@v2
      - name: Deploy PR Preview
        uses: rossjrw/pr-preview-action@v1.6.2
        with:
          source-dir: ./_output/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
